# 所有环境公用的配置属性
management:
  endpoint:
    health:
      show-details: always  #环境变量写法${SOME_ENV} java -jar *.jar --SOME_ENV=always
  #激活所有的actuator端点
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app-name: spring-boot-demo
  author: wxywizard
  email: xxx@email.com

#默认启动方式
spring:
  profiles:
    active: dev
# 连字符
---
# profile=x的专用属性，也就是某个环境下的专用属性
# 开发环境
spring:
  profiles: dev

---
# profile=y的专用属性，也就是某个环境下的专用属性
# 生产环境

spring:
  profiles: prod

server:
  tomcat:
    max-threads: 300
    max-connections: 1000

