spring:
  datasource:
    url: jdbc:mysql://172.20.36.215:3306/content_center?characterEncoding=utf8
    hikari:
      username: root
      password: Wizard@123
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    #服务名称尽量用-,不要用_,不要用特殊字符
    name: content-center
  cloud:
    nacos:
      discovery:
        #指定 nacos server的地址
        server-addr: 172.20.36.215:8848
server:
  port: 8041
logging:
  level:
    # 这样，这个包下的所有mapper都会打印出执行的SQL
    com.wxywizard.contentcenter.dao: debug